### ISSUE TITLE
rss feed is not working.

### ISSUE THREAD

**Issue by iolo** [CocoaPods/feeds.cocoapods.org#280]
internal server error on rss feed:

http://feeds.cocoapods.org/new-pods.rss

```
curl -v 'http://feeds.cocoapods.org/new-pods.rss'
*   Trying 104.18.60.114...
* Connected to feeds.cocoapods.org (104.18.60.114) port 80 (#0)
> GET /new-pods.rss HTTP/1.1
> Host: feeds.cocoapods.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 11 Mar 2016 05:35:26 GMT
< Content-Type: text/html;charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d1ab5e073b63a483e8917ed63b5ea6c311457674524; expires=Sat, 11-Mar-17 05:35:24 GMT; path=/; domain=.cocoapods.org; HttpOnly
< Vary: Accept-Encoding
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Via: 1.1 vegur
< Server: cloudflare-nginx
< CF-RAY: 281ca4952e6509e2-ICN
<
* Connection #0 to host feeds.cocoapods.org left intact
<h1>Internal Server Error</h1>
```

**Comment by segiddins** [comment]
```
heroku[router]: at=info method=GET path="/new-pods.rss" host=feeds.cocoapods.org request_id=8de05555-5293-4c02-a350-b6ed77a2e05f fwd="173.11.117.45,199.27.128.179" dyno=web.1 connect=1ms service=215ms status=500 bytes=332

app[web.1]: TypeError - wrong argument type nil (expected String):

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:106:in `render'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:106:in `markdown'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:81:in `rss_item_description'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:39:in `block (2 levels) in feed'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:38:in `each'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:68:in `configure_rss_item'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:38:in `block in feed'

app[web.1]:     /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/rss/maker/base.rb:402:in `make'

app[web.1]:     /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/rss/maker/base.rb:438:in `make'

app[web.1]:     /app/lib/cocoapods_notifier/rss.rb:30:in `feed'

app[web.1]:     /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/rss/maker.rb:28:in `make'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'

app[web.1]:     /app/app/controllers/web_controller.rb:55:in `block in <class:WebController>'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `catch'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:87:in `start'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'

app[web.1]: 173.11.117.45, 199.27.128.179 - - [11/Mar/2016 05:56:00] "GET /new-pods.rss HTTP/1.1" 500 - 0.2136

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `<main>'

app[web.1]:     /app/vendor/bundle/ruby/2.1.0/bin/thin:23:in
```

**Comment by iolo** [comment]
not working... again... :'(
